# Generated by Django 3.2.2 on 2021-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ije', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alternate_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
