# Generated by Django 3.2.2 on 2021-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ije', '0002_auto_20210630_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='file',
            field=models.ImageField(default=0, upload_to='uploads/'),
        ),
    ]
