# Generated by Django 3.2.2 on 2021-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ije', '0004_remove_manuscript_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='keywords',
            field=models.TextField(),
        ),
    ]
