# Generated by Django 3.2.2 on 2021-07-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ije', '0007_manuscript_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('IN PROCESSING', 'IN PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL '), ('FAILED', 'FAILED')], default='SUBMITTED', max_length=20),
        ),
    ]
